# Specify multiple camera configs to be combined into one multi-view dataset
experiment: "single"
epochs: 1
f: 1
batch_size: 128
img_size: [256, 256]
dataset_path: "./data"
weather: 36
lr: 0.0001
T: 1000
checkpoint: ""
cameras: [
]
roundshot: "acbdefc4ab9401cd8ae0c16b3d25aa58"